/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./src/components/AppFooter.vue')['default']
    CleaningRecord: typeof import('./src/components/CleaningRecordCard.vue')['default']
    CleaningRecordCard: typeof import('./src/components/CleaningRecordCard.vue')['default']
    CleaningScheduleCard: typeof import('./src/components/CleaningScheduleCard.vue')['default']
    copy: typeof import('./src/components/GuestCard copy.vue')['default']
    Floor: typeof import('./src/components/FloorCard.vue')['default']
    FloorCard: typeof import('./src/components/FloorCard.vue')['default']
    GuestCard: typeof import('./src/components/GuestCard.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    LivingRecordCard: typeof import('./src/components/LivingRecordCard.vue')['default']
    RoomCard: typeof import('./src/components/RoomCard.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    StaffCard: typeof import('./src/components/StaffCard.vue')['default']
    TopBar: typeof import('./src/components/TopBar.vue')['default']
  }
}
