/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/cleaningRecords/': RouteRecordInfo<'/cleaningRecords/', '/cleaningRecords', Record<never, never>, Record<never, never>>,
    '/cleaningRecords/[id]/': RouteRecordInfo<'/cleaningRecords/[id]/', '/cleaningRecords/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/cleaningRecords/[id]/edit': RouteRecordInfo<'/cleaningRecords/[id]/edit', '/cleaningRecords/:id/edit', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/cleaningRecords/new': RouteRecordInfo<'/cleaningRecords/new', '/cleaningRecords/new', Record<never, never>, Record<never, never>>,
    '/cleaningSchedules/': RouteRecordInfo<'/cleaningSchedules/', '/cleaningSchedules', Record<never, never>, Record<never, never>>,
    '/cleaningSchedules/[id]/': RouteRecordInfo<'/cleaningSchedules/[id]/', '/cleaningSchedules/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/cleaningSchedules/[id]/edit': RouteRecordInfo<'/cleaningSchedules/[id]/edit', '/cleaningSchedules/:id/edit', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/cleaningSchedules/new': RouteRecordInfo<'/cleaningSchedules/new', '/cleaningSchedules/new', Record<never, never>, Record<never, never>>,
    '/floors/': RouteRecordInfo<'/floors/', '/floors', Record<never, never>, Record<never, never>>,
    '/floors/[id]/': RouteRecordInfo<'/floors/[id]/', '/floors/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/floors/[id]/edit': RouteRecordInfo<'/floors/[id]/edit', '/floors/:id/edit', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/floors/new': RouteRecordInfo<'/floors/new', '/floors/new', Record<never, never>, Record<never, never>>,
    '/guests/': RouteRecordInfo<'/guests/', '/guests', Record<never, never>, Record<never, never>>,
    '/guests/[id]/': RouteRecordInfo<'/guests/[id]/', '/guests/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/guests/[id]/edit': RouteRecordInfo<'/guests/[id]/edit', '/guests/:id/edit', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/guests/new': RouteRecordInfo<'/guests/new', '/guests/new', Record<never, never>, Record<never, never>>,
    '/livingRecords/': RouteRecordInfo<'/livingRecords/', '/livingRecords', Record<never, never>, Record<never, never>>,
    '/livingRecords/[id]/': RouteRecordInfo<'/livingRecords/[id]/', '/livingRecords/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/livingRecords/[id]/edit': RouteRecordInfo<'/livingRecords/[id]/edit', '/livingRecords/:id/edit', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/livingRecords/new': RouteRecordInfo<'/livingRecords/new', '/livingRecords/new', Record<never, never>, Record<never, never>>,
    '/login': RouteRecordInfo<'/login', '/login', Record<never, never>, Record<never, never>>,
    '/register': RouteRecordInfo<'/register', '/register', Record<never, never>, Record<never, never>>,
    '/requests/': RouteRecordInfo<'/requests/', '/requests', Record<never, never>, Record<never, never>>,
    '/requests/guests_by_city/': RouteRecordInfo<'/requests/guests_by_city/', '/requests/guests_by_city', Record<never, never>, Record<never, never>>,
    '/requests/guests_by_guest_period/': RouteRecordInfo<'/requests/guests_by_guest_period/', '/requests/guests_by_guest_period', Record<never, never>, Record<never, never>>,
    '/requests/guests_by_room_period/': RouteRecordInfo<'/requests/guests_by_room_period/', '/requests/guests_by_room_period', Record<never, never>, Record<never, never>>,
    '/requests/n_free_rooms/': RouteRecordInfo<'/requests/n_free_rooms/', '/requests/n_free_rooms', Record<never, never>, Record<never, never>>,
    '/requests/quarterly_report/': RouteRecordInfo<'/requests/quarterly_report/', '/requests/quarterly_report', Record<never, never>, Record<never, never>>,
    '/requests/staff_by_guest_day/': RouteRecordInfo<'/requests/staff_by_guest_day/', '/requests/staff_by_guest_day', Record<never, never>, Record<never, never>>,
    '/rooms/': RouteRecordInfo<'/rooms/', '/rooms', Record<never, never>, Record<never, never>>,
    '/rooms/[id]/': RouteRecordInfo<'/rooms/[id]/', '/rooms/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/rooms/[id]/edit': RouteRecordInfo<'/rooms/[id]/edit', '/rooms/:id/edit', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/rooms/new': RouteRecordInfo<'/rooms/new', '/rooms/new', Record<never, never>, Record<never, never>>,
    '/staff/': RouteRecordInfo<'/staff/', '/staff', Record<never, never>, Record<never, never>>,
    '/staff/[id]/': RouteRecordInfo<'/staff/[id]/', '/staff/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/staff/[id]/edit': RouteRecordInfo<'/staff/[id]/edit', '/staff/:id/edit', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/staff/new': RouteRecordInfo<'/staff/new', '/staff/new', Record<never, never>, Record<never, never>>,
  }

  /**
   * Route file to route info map by unplugin-vue-router.
   * Used by the volar plugin to automatically type useRoute()
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/pages/index.vue': {
      routes: '/'
      views: never
    }
    'src/pages/cleaningRecords/index.vue': {
      routes: '/cleaningRecords/'
      views: never
    }
    'src/pages/cleaningRecords/[id]/index.vue': {
      routes: '/cleaningRecords/[id]/'
      views: never
    }
    'src/pages/cleaningRecords/[id]/edit.vue': {
      routes: '/cleaningRecords/[id]/edit'
      views: never
    }
    'src/pages/cleaningRecords/new.vue': {
      routes: '/cleaningRecords/new'
      views: never
    }
    'src/pages/cleaningSchedules/index.vue': {
      routes: '/cleaningSchedules/'
      views: never
    }
    'src/pages/cleaningSchedules/[id]/index.vue': {
      routes: '/cleaningSchedules/[id]/'
      views: never
    }
    'src/pages/cleaningSchedules/[id]/edit.vue': {
      routes: '/cleaningSchedules/[id]/edit'
      views: never
    }
    'src/pages/cleaningSchedules/new.vue': {
      routes: '/cleaningSchedules/new'
      views: never
    }
    'src/pages/floors/index.vue': {
      routes: '/floors/'
      views: never
    }
    'src/pages/floors/[id]/index.vue': {
      routes: '/floors/[id]/'
      views: never
    }
    'src/pages/floors/[id]/edit.vue': {
      routes: '/floors/[id]/edit'
      views: never
    }
    'src/pages/floors/new.vue': {
      routes: '/floors/new'
      views: never
    }
    'src/pages/guests/index.vue': {
      routes: '/guests/'
      views: never
    }
    'src/pages/guests/[id]/index.vue': {
      routes: '/guests/[id]/'
      views: never
    }
    'src/pages/guests/[id]/edit.vue': {
      routes: '/guests/[id]/edit'
      views: never
    }
    'src/pages/guests/new.vue': {
      routes: '/guests/new'
      views: never
    }
    'src/pages/livingRecords/index.vue': {
      routes: '/livingRecords/'
      views: never
    }
    'src/pages/livingRecords/[id]/index.vue': {
      routes: '/livingRecords/[id]/'
      views: never
    }
    'src/pages/livingRecords/[id]/edit.vue': {
      routes: '/livingRecords/[id]/edit'
      views: never
    }
    'src/pages/livingRecords/new.vue': {
      routes: '/livingRecords/new'
      views: never
    }
    'src/pages/login.vue': {
      routes: '/login'
      views: never
    }
    'src/pages/register.vue': {
      routes: '/register'
      views: never
    }
    'src/pages/requests/index.vue': {
      routes: '/requests/'
      views: never
    }
    'src/pages/requests/guests_by_city/index.vue': {
      routes: '/requests/guests_by_city/'
      views: never
    }
    'src/pages/requests/guests_by_guest_period/index.vue': {
      routes: '/requests/guests_by_guest_period/'
      views: never
    }
    'src/pages/requests/guests_by_room_period/index.vue': {
      routes: '/requests/guests_by_room_period/'
      views: never
    }
    'src/pages/requests/n_free_rooms/index.vue': {
      routes: '/requests/n_free_rooms/'
      views: never
    }
    'src/pages/requests/quarterly_report/index.vue': {
      routes: '/requests/quarterly_report/'
      views: never
    }
    'src/pages/requests/staff_by_guest_day/index.vue': {
      routes: '/requests/staff_by_guest_day/'
      views: never
    }
    'src/pages/rooms/index.vue': {
      routes: '/rooms/'
      views: never
    }
    'src/pages/rooms/[id]/index.vue': {
      routes: '/rooms/[id]/'
      views: never
    }
    'src/pages/rooms/[id]/edit.vue': {
      routes: '/rooms/[id]/edit'
      views: never
    }
    'src/pages/rooms/new.vue': {
      routes: '/rooms/new'
      views: never
    }
    'src/pages/staff/index.vue': {
      routes: '/staff/'
      views: never
    }
    'src/pages/staff/[id]/index.vue': {
      routes: '/staff/[id]/'
      views: never
    }
    'src/pages/staff/[id]/edit.vue': {
      routes: '/staff/[id]/edit'
      views: never
    }
    'src/pages/staff/new.vue': {
      routes: '/staff/new'
      views: never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the volar plugin to automatically type useRoute()
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}
