# Generated by Django 6.0.1 on 2026-01-25 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='is_occupied',
        ),
    ]
