# Generated by Django 6.0.1 on 2026-01-25 10:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_app', '0002_remove_room_is_occupied'),
    ]

    operations = [
        migrations.CreateModel(
            name='CleaningRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cleaning_date', models.DateField(verbose_name='Дата уборки')),
                ('floor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cleaning_records', to='hotel_app.floor', verbose_name='Этаж')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cleaning_records', to='hotel_app.staff', verbose_name='Служащий')),
            ],
            options={
                'unique_together': {('floor', 'cleaning_date')},
            },
        ),
    ]
